baseURL = 'https://www.cloudslit.xyz/'
languageCode = 'en-us'
title = 'CLOUDSLIT'
keywords = "cloudslit,ipfs,safe,network"
theme = "SimpleIntro"

[params]
    mainbg = "https://picsum.photos/1920/1080?blur=5"
    description= "CLOUDSLIT is a research and open source organization for zero trust architecture. We will gradually open source the projects we have incubated and ongoing projects to make our contribution to the zero-trust ecosystem. If you are also interested, or have any suggestions, please let us know and let us know. Let's work together to promote the construction of a zero-trust ecosystem."
    name = "CLOUDSLIT"
    mainTitle = "CLOUDSLIT"
    mainText = "Build a global web3 decentralized zero-trust security network，Building Cyber Sovereignty."

[menus]
    [[menu.main]]
        identifier = "Projects"
        name = "Projects"
        url = "#projects"
        weight="1"
    [[menu.main]]
        identifier = "Blogs"
        name = "Blogs"
        url = "http://www.cloudslit.xyz/cloudslit_blog/"
        weight="2"
    [[menu.main]]
        identifier = "Docs"
        name = "Docs"
        url = "http://www.cloudslit.xyz/cloudslit_docs/"
        weight="3"
    [[menu.main]]
        identifier = "OpenSource"
        name = "OpenSource"
        url = "https://github.com/cloudslit"
        weight="4"
    [[menu.main]]
        identifier = "About"
        name = "About"
        url = "http://www.cloudslit.xyz/cloudslit_about"
        weight="5"